[build]
  base = "netlify-dashboard"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api.php"
  to = "https://dersbende.com/api.php"
  status = 200
  force = true

[[redirects]]
  from = "/egg-prices"
  to = "https://basmakcitavukculuk.com/"
  status = 200
  force = true

[[redirects]]
  from = "/egg-prices-image"
  to = "https://basmakcitavukculuk.com/indexyumurta.php"
  status = 200
  force = true

[[redirects]]
  from = "/yahoo-proxy/*"
  to = "https://query1.finance.yahoo.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/fao/*"
  to = "https://fpma.fao.org/giews/v4/global/price_module/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
