-- İhracat Onayları verileri
-- Oluşturulma: 2026-02-04 23:34:11

DROP TABLE IF EXISTS `oner_i_hracat_onaylari`;

CREATE TABLE `oner_i_hracat_onaylari` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `onay_numarasi` VARCHAR(500),
  `firmanin_unvani` VARCHAR(500),
  `urunun_kategorisi` TEXT,
  `ihracat_onayi_aldigi_ulke` VARCHAR(500),
  `onayin_durumu` VARCHAR(500),
  `gosterim_icin_deger` DOUBLE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 130 satır veri ekleniyor...

INSERT INTO `oner_i_hracat_onaylari` (`onay_numarasi`, `firmanin_unvani`, `urunun_kategorisi`, `ihracat_onayi_aldigi_ulke`, `onayin_durumu`, `gosterim_icin_deger`) VALUES
  ('TR-70-0024', 'AK GIDA SANAYİVE TİCARET A.Ş', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-54-0037', 'AK GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0404', 'AKAVİ SÜT VE GIDA SANAYİ VE TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0038', 'AKOVA SÜT VE GIDA MAMULLERİ SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-09-0469', 'ALTINKÖY GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-39-0345', 'ASLANAĞA ÇİFTLİĞİ SÜT ÜRÜNLERİ SAN.VE TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-10-0386', 'ASTOSAN SÜT VE GIDA MAMULLERİ SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-39-0022', 'BAHÇIVAN GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-51-0023', 'BAKKALBAŞIOĞLU SÜT ÜRÜNLERİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-03-0355', 'BOLVADİN GIDA İNŞ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-61-0125', 'BÜYÜKLİMAN SÜT ÜRÜNLERİ SANAYİ VE HAYVANCILIK TİC.LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0069', 'CİCİ SÜT SANAYİVE TİCARET A.Ş', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0730', 'DEMİRELLER AKARYAKIT NAKLİYAT SANAYİ VE TİCARET LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-35-0098', 'DİMES GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-15-0027', 'DURANLAR SÜT SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-07-1965', 'EKSO SÜT VE GIDA MAMÜLLERİ SANAYİ VE TİCARET A.Ş', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-03-0166', 'EMRULLAHOĞLU ARI SÜT URRUNLARI', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0085', 'ENKA SÜT VE GIDA MAMULLERİ SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-10-1148', 'GÖNENLİ SÜT VE SÜT ÜRÜNLERİ GIDA SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0026', 'GÜNDOĞDU GIDA SÜT ÜRÜNLERİ SAN VE DIŞ TİC A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-34-1444', 'HAKTAN PEYNİRCİLİK GIDA SAN.VE TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0278', 'HASAN TÜREK ÇİFTLİĞİ HAYVANCILIK VE TARIM ÜRÜNLERİ GIDA ÜRETİM İÇ VE DIŞ TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-16-0115', 'İTİMAT PEYNİRCİLİK SÜT VE SÜT ÜRÜNLERİ İMALAT PAZARLAMA SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0762', 'İZİ SÜT VE GIDA MAMULERİ SAN.TİC.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-59-0023', 'KAANLAR GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-61-0029', 'KARADENİZ KARDEŞLER GIDA SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0101', 'KEMPO GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-17-0666', 'LİZETTA TARIM VE SÜT ÜRÜNLERİ SANAYİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-59-0031', 'MALKARA BİRLİK SÜT VE SÜT MAMULLERİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0582', 'MEYSÜT MEYVE SÜT VE GIDA MAM.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0047', 'MEYSÜT MEYVE SÜT VE GIDA MAM.SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-09-0385', 'MİLAY SÜT VE SÜT ÜRÜNLERİ GIDA SANAYİ TİCARET ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-54-0066', 'MİLKON SÜT VE GIDA MAMULLERİ SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-64-0025', 'MURATBEY GIDA SANAYİVE TİCARET ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-54-0035', 'ÖZGÜLLÜ SÜT MAMÜLLERİ ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-42-0104', 'PANAGRO TARIM HAYVANCILIK GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-26-0027', 'PINAR SÜT MAM.SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-35-0069', 'PINAR SÜT MAMULLERİ SANAYİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-35-0222', 'REHA SÜT ÜRÜNLERİ SANAYİ TİCARET LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0248', 'RELLA GIDA SANAYİ TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-16-0070', 'SEKSÜT ENDÜSTRİSİ KURUMU A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-09-0307', 'SEKSÜT ENDÜSTRİSİ KURUMU A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-70-0075', 'SLAVA SÜT VE SÜT ÜRÜNLERİ GIDA SANAYİ TİC.LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-45-0049', 'STANDART BESİCİLİK HAYVANCILIK VE GIDA ÜRÜNLERİ SAN.TİC.LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-16-0111', 'SÜTAŞ SÜT ÜRÜNLERİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-35-0673', 'SÜTAŞ SÜT ÜRÜNLERİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-68-0024', 'SÜTAŞ SÜT ÜRÜNLERİ A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-03-2025', 'SÜTÇÜOĞLU KLASİK SÜT ÜRÜNLERİ TİC.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-15-0031', 'SÜTOFİS GIDA MAMULLERİ SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-17-0028', 'TAHSİLDAROĞLU SÜT ÜRÜNLERİ SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-20-0023', 'TARIM KREDİ SÜT ÜRÜNLERİ ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-22-0290', 'TARIM-TAC TARIM TARIMSAL GIDA SANAYİ PROJE VE MÜHENDİSLİK HİZMETLERİ ARAŞTIRMA ÜRETİM VE PAZARLAMA A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-10-1935', 'TEKSÜT SÜT MAMÜLLERİ SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-68-0031', 'UĞURAY SÜT A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-59-0028', 'ÜNAL PEYNİRCİLİK İTHALAT İHRACAT TİCARET LTD. ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-33-0227', 'YÖRÜK SÜT ANONİM ŞİRKETİ', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-07-1942', 'YÖRÜKOĞLU SÜT VE SÜT ÜRÜNLERİ SAN.TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-07-0388', 'YÖRÜKOĞLU SÜT VE ÜRÜNLERİ SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Geçerli', 100.0),
  ('TR-35-0894', 'AK GIDA SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'İptal', 0.0),
  ('TR-35-0889', 'AK GIDA SAN.VE TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'İptal', NULL),
  ('TR-33-0056', 'BAŞARAN PEYNİRCİLİK VE GIDA SANAYİ LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-07-1966', 'EKİCİLER SÜT GIDA TARIM HAYVANCILIK SANAYİ VE TİC.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-19-0065', 'EREN GIDA ENDÜSTRİSİ SAN. VE TİC.LTD.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-05-0152', 'FİMAR HAYVANCILIK GIDA ÜRÜNLERİ SAN.TİC.A.Ş', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-54-0028', 'GÜNEŞOĞLU SÜT GIDA SANAYİVE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-33-0222', 'GÜNEY SÜT SAN. VE GIDA MAD.TİC A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'İptal', NULL),
  ('TR-35-0315', 'HAS ÇİFTLİK GIDA TARIM HAYVANCILIK SANAYİ VE TİCARET LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'İptal', NULL),
  ('TR-42-0056', 'İZİ SÜT VE GIDA MAMULERİ SAN.TİC.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-09-0252', 'KARA SÜT İMALAT PAZ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-16-0053', 'MBH GIDA SANAYİ TİCARET A.Ş', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'İptal', NULL),
  ('TR-70-0057', 'MİLKMAN SÜT VE SÜT ÜRÜNLERİ GIDA SANAYİ TİC.A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-33-0094', 'NAVİMARFOOD GIDA İMALATI VE GIDA MADDELERİ YAT.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-45-0097', 'TAKIŞ GIDA SANAYİ VE TİCARET LTD.ŞTİ.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-42-0099', 'TORUNOĞLU SÜT VE GIDA MAMULLERİ SAN.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-32-0031', 'YAYLA SÜT FABRİKASI DURMUŞ GÜRDAL', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-10-1936', 'YÖRSAN GIDA MAMULLERİ SANAYİ VE TİCARET A.Ş.', 'PASTÖRİZE SÜT VE DİĞER SÜT ÜRÜNLERİ', 'Çin', 'Süresi Bitmiş', NULL),
  ('TR-39-0024', 'AK GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'SÜT VE SÜT ÜRÜNLERİ, UHT SÜT, YOĞURT, AYRAN ÜRETİMİ', 'Rusya', 'Geçerli', 100.0),
  ('TR-16-0030', 'NATURA GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'DONDURMA, SÜTLÜ BUZ, YENİLEBİLİR BUZ ÜRÜNLERİ, DONDURULMUŞ KEK ÜRETİMİ', 'Rusya', 'Geçerli', 100.0),
  ('TR-35-0069', 'PINAR SÜT MAMULLERİ SANAYİİ ANONİM ŞİRKETİ', 'SÜT VE SÜT ÜRÜNLERİ ÜRETİMİ, PASTÖRİZE SÜT, PASTÖRİZE SÜTLAÇ, SÜT TOZU, ORGANİK SÜT TOZU, PEYNİR ALTI SUYU TOZU, DEMİNERALİZE PEYNİR ALTI SUYU TOZU, PEYNİRLER (TAZE SERT PEYNİR, MARİNE EDİLMİŞ PEYNİR, KAŞAR, TAZE PEYNİR, İŞLENMİŞ PEYNİR (ÜÇGEN, KAYMAKLI, DİLİMLİ) ), YOĞURT, AYRAN, TEREYAĞI, PASTÖRİZE KREMA, LABNE PEYNİRİ, EKŞİ KREMA, KREMA (YÜZDE 30 YAĞLI), PUDİNG TOZU, ŞANTİ KREMA TOZU', 'Rusya', 'Geçerli', 100.0),
  ('TR-26-0027', 'PINAR SÜT MAMÜLLERİ SANAYİ A.Ş.', 'SÜT ÜRETİMİ', 'Rusya', 'Geçerli', 100.0),
  ('TR-45-0248', 'RELLA GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'PEYNİR (MOZZARELLA) ÜRETİMİ', 'Rusya', 'Geçerli', 100.0),
  ('TR-16-0070', 'SEKSÜT ENDÜSTRİSİ KURUMU A.Ş.', 'SÜT VE SÜT ÜRÜNLERİ ÜRETİMİ, ASEPTİK PASTÖRİZE SÜT (KATKISIZ, BEBEKLERE ÖZEL AROMALI), PEYNİR (ÇEÇİL, KAYMAK, SERT PEYNİR, TOSTLUK, ÜÇGEN İŞLENMİŞ PEYNİR, SERT PEYNİRLER), TEREYAĞI, AYRAN, YOĞURT (KREMALI, KREMASIZ) ), PASTÖRİZE SÜT (KATKISIZ, MEYVE PÜRELİ, AROMALI), SALEP, SICAK ÇİKOLATA, EKŞİ KREMA', 'Rusya', 'Geçerli', 100.0),
  ('TR-16-0111', 'SÜTAŞ SÜT ÜRÜNLERİ A.Ş.', 'SÜT VE SÜT ÜRÜNLERİ ÜRETİMİ, UHT SÜT, YOĞURT, AYRAN, MEYVELİ YOĞURT, PEYNİR, SÜZME PEYNİR, TAZE PEYNİR, PROBİYOTİKLİ YOĞURT, BEBE YOĞURDU, KURU ÜRÜNLER, SÜTLÜ TATLILAR, TEREYAĞI', 'Rusya', 'Zaman kısıtlamaları', 100.0),
  ('TR-20-0023', 'TARIM KREDİ SÜT ÜRÜNLERİ ANONİM ŞİRKETİ', 'SÜT ÜRETİMİ', 'Rusya', 'İzin verilmiş', 100.0),
  ('TR-59-K-000977', 'ÜNİLEVER SANAYİ VE TİCARET TÜRK ANONİM ŞİRKETİ (ALGİDA)', 'SÜT TOZU VE PASTÖRİZE KREMADAN YOĞURT DAHİL DONDURMA ÜRETİMİ', 'Rusya', 'İzin verilmiş', 100.0),
  ('TR-46-0022', 'AK GIDA SAN. TİC. A.S. KAHRAMANMARAS PLANT', 'SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-70-0024', 'AK GIDA SAN. VE TIC. A.Ş', 'PEYNİR, TEREYAĞI, KREMA, SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-35-0889', 'AK GIDA SANAYİ VE TIC. A.Ş', 'PEYNİR', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0038', 'AKOVA SÜT VE GIDA MAM. SAN. VE TIC. A.Ş.', 'PEYNİR, TEREYAĞI, KREMA', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-17 - 0022', 'AKPINAR SÜT ÜRÜNLERİ SAN. TİC. LTD. ŞTİ.', 'PEYNİR / LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0971', 'AKZON ENERJI VE ÇEVRE TEKNOLOJILERI GIDA SAN. VE TIC. A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-17 -0023', 'ALTINKILIÇ GIDA VE SÜT SAN.VE TİC.A.Ş', 'PEYNİR, SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-09-0469', 'ALTINKÖY GIDA SAN. VE.TİC.A.Ş', 'PEYNİR', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-39-0345', 'ASLANAGA CİFTLİGİ SUT ÜRÜNLERİ SAN. VE TİC. AS', 'PEYNİR, KREMA, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-- 390022', 'BAHCİVAN FOOD INDUSTRY TRADE INC', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-15-0027', 'DURANLAR SÜT SANAYİ VE TİCARET A.Ş.', 'PEYNİR, KREMA, TEREYAĞI, YOĞURT, AYRAN', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-16-0027', 'EKER SÜT ÜRÜNLERİ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-07-0066', 'EKİCİLER SÜT GİDA TARİM HAYVANCILIK SAN. VE TIC. A.Ş.', 'PEYNİR', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-07-0065', 'EKSO SÜT VE GIDA MAMULLERİ SAN. VE TIC. A.Ş.', 'PEYNİR ALTI SUYU TOZU, SÜT TOZU', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0085', 'ENKA SÜT VE GIDA MAM. SAN. VE TIC. A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0);

INSERT INTO `oner_i_hracat_onaylari` (`onay_numarasi`, `firmanin_unvani`, `urunun_kategorisi`, `ihracat_onayi_aldigi_ulke`, `onayin_durumu`, `gosterim_icin_deger`) VALUES
  ('TR-19-0065', 'EREN GIDA ENDÜSTRİSİ SAN. VE TİC. LTD. ŞTİ.', 'PEYNİR, TEREYAĞI, KREMA', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-05-0152', 'FİMAR MERMER MADENCİLİK İNŞAAT AKARYAKIT TURİZM TARIM SERACILIK HAYVANCILIK GIDA ÜRÜNLERİ TİC.SAN.A.Ş', 'PEYNİR, TEREYAĞI, KREMA, LABNE, MOZZARELLA', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-10-1148', 'GÖNENLİ SÜT VE SÜT ÜRÜNLERİ GIDA SAN.VE TİC.A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-35-0999', 'GURSUT BESİCİLİK GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-45-0026', 'GÜNDOĞDU GIDA SÜT ÜRÜNLERİ SAN.VE DIŞ TİCARET A.Ş', 'PEYNİR, TEREYAĞI', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-59-0023', 'KAANLAR GIDA SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'PEYNİR, TEREYAĞI, KREMA, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR45-0101', 'KEMPOSTAR GIDA SAN.VE TIC.A.S', 'SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-1069', 'KONSÜT GIDA A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0059', 'KUZUCU SÜT MAM. NAK. VE GIDA SAN. VE TIC. A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-17 -0666', 'LİZETTA TARIM VE SÜT ÜRÜNLERİ SANAYİ A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-59-0031', 'MALKARA BIRLIK SÜT VE SÜT MAMULLERI ANONIM ŞIRKETI', 'SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0047', 'MEYSÜT MEYVE SÜT VE GIDA MAM. SAN. TIC. A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-16-0053', 'MİLK ACADEMY SÜT ÜRÜNLERİ SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-54-0066', 'MİLKON SÜT VE GIDA MAMULLERİ SANAYİ VE TİCARET ANONİM ŞİRKETİ', 'SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-64-0025', 'MURATBEY GIDA SANAYİ VE TİCARET A.Ş.', 'PEYNİR, TEREYAĞI, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-33-0094', 'NAVİMARFOOD GIDA İMALATI VE GIDA MADDELERİ YAT ÜRT.İNŞ.PAZ.SAN.VE TİC.LTD.ŞTİ', 'PEYNİR, TEREYAĞI, KREMA, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-55-0043', 'OTAT GIDA SAN. VE TİC. LTD STI.', 'PEYNİR, TEREYAĞI, LABNE, KREMA', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-0104', 'PANAGRO TARİM HAYVANCILIK GIDA SAN. VE TIC. A.Ş.', 'PEYNİR, KREMA, TEREYAĞI, SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-35-0069', 'PINAR SÜT ÜRÜNLERİ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-35-0222', 'REHA SÜT ÜRÜNLERİ SAN.VE TİC.LTD.ŞTI.', 'PEYNİR', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-45-0248', 'RELLA GIDA SANAYİ VE TİCARET A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-35-0673', 'SÜTAŞ SÜT ÜRÜNLERİ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-16-0111', 'SÜTAŞ SÜT ÜRÜNLERİ A.Ş.', 'PEYNİR, TEREYAĞI, SÜT, KREMA', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-20-0023', 'TARIM KREDİ SÜT ÜRÜNLERİ A.Ş.', 'PEYNİR, TEREYAĞI, KREMA, SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-10-0035', 'TEKSÜT SÜT MAMÜLLERİ SAN.VE.TİC.AŞ', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-59-K-000977', 'UNILEVER SANAYI VE TİCARET TÜRK ANONIM ŞIRKETI', NULL, 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-42-K-002922', 'UNİLEVER SAN. VE TİC. TÜRK A.Ş. KONYA ALGIDA FABRİKASI ŞUBESİ', 'SÜT', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-46-0132', 'YASAR DONDURMA VE GIDA MADDELERİ A.S', 'PEYNİR, TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-07-0388', 'YÖRÜKOĞLU SÜT VE ÜRÜNLERİ SAN.TİC.A.Ş', 'PEYNİR', 'Sudi Arabistan', 'Geçerli', 100.0),
  ('TR-07-0042', 'YÖRÜKOĞLU SÜT VE ÜRÜNLERİ SAN.TİC.A.Ş.', 'TEREYAĞI, KREMA, SÜT, LABNE', 'Sudi Arabistan', 'Geçerli', 100.0);
